<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'nGen\Zf2Entity\Model\SharedEntityStatistics'                 => __DIR__ . '//src/Entity/Model/SharedEntityStatistics.php',
  'nGen\Zf2Entity\Model\Tag'                                    => __DIR__ . '//src/Entity/Model/Tag.php',
  'nGen\Zf2Entity\Model\EntityLog'                              => __DIR__ . '//src/Entity/Model/EntityLog.php',
  'nGen\Zf2Entity\Model\EntityStatistics'                       => __DIR__ . '//src/Entity/Model/EntityStatistics.php',
  'nGen\Zf2Entity\Model\EntityTag'                              => __DIR__ . '//src/Entity/Model/EntityTag.php',
  'nGen\Zf2Entity\Controller\EntityStatisticsController'        => __DIR__ . '//src/Entity/Controller/EntityStatisticsController.php',
  'nGen\Zf2Entity\Service\EntityStatisticsService'              => __DIR__ . '//src/Entity/Service/EntityStatisticsService.php',
  'nGen\Zf2Entity\Service\ChildEntityServiceInterface'          => __DIR__ . '//src/Entity/Service/ChildEntityServiceInterface.php',
  'nGen\Zf2Entity\Mapper\EntityStatisticsDbMapper'              => __DIR__ . '//src/Entity/Mapper/EntityStatisticsDbMapper.php',
  'nGen\Zf2Entity\Mapper\Factory\EntityStatisticsMapperFactory' => __DIR__ . '//src/Entity/Mapper/Factory/EntityStatisticsMapperFactory.php',
  'nGen\Zf2Entity\Module'                                       => __DIR__ . '//Module.php',
);
