<?php
    $this -> headTitle($title);
    $params = $route['params'];
    $options = $route['options'];
?>
<h1><?php echo isset($pluralTitle) ? $pluralTitle: $title; ?></h1>
<?php echo isset($subTitle) ? "<h5>{$subTitle}</h5>" : ''; ?>

<p>
    <?php $params['action'] = 'add'; ?>
    <a class="btn btn-primary btn-sm" href="<?php echo $this -> url($mainRouteName, $params, $options); ?>">Add new <?php echo $title; ?></a>
</p>
<?php
    $GLOBALS['mainRouteName'] = $mainRouteName;
    if(isset($subRouteName)) $GLOBALS['subRouteName'] = $subRouteName;
    function getRouteLink($view, $route, $params, $options, $record = false) {

        if(is_array($route['name'])) {
            switch($route['name']['type']) {
                case "from_view":
                    global ${$route['name']['value']};
                    $route_name = ${$route['name']['value']};
                break;
            }
        } else { 
            $route_name = $route['name'];
        }

        $rParams = array();
        if(isset($route['params']) && count($route['params'])) {
            foreach($route['params'] as $r_param_name => $r_params) {
                if(isset($r_params['type']) && isset($r_params['value'])) {
                    switch($r_params['type']) {
                        case "static":
                            $r_param_value = $r_params['value'];
                        break;
                        case "from_record":
                            $r_param_value = $record -> $r_params['value'];
                        break;
                        case "from_view":
                            global ${$r_params['value']};
                            $r_param_value = ${$r_params['value']};
                        break;
                        case "unlink":
                            unset($params[$r_params['value']]);
                        break;
                    }
                    $rParams[$r_param_name] = $r_param_value;
                } else continue;
            }
        }

        if(isset($route['merge_current_params']) && $route['merge_current_params'] === true) {
            $rParams = array_merge($params, $rParams);
        }

        $rOptions = array();
        if(isset($route['options']) && count($route['options'])) {
            foreach($route['options'] as $rKey => $rOptionType) {
                $r_type = array();
                foreach($rOptionType as $r_option_name => $r_options) {
                    if(isset($r_options['type']) && isset($r_options['value'])) {
                        switch($r_options['type']) {
                            case "static":
                                $r_option_value = $r_options['value'];
                            break;
                            case "from_record":
                                $r_option_value = $record -> $r_options['value'];
                            break;
                            case "from_view":
                                global ${$r_options['value']};
                                $r_option_value = ${$r_options['value']};
                            break;
                            case "unlink":
                                unset($options[$r_options['value']]);
                            break;
                        }
                        $r_type[$r_option_name] = $r_option_value;
                    } else continue;
                }
                $rOptions[$rKey] = $r_type;
            }
        }
        $rOptions = array_merge($options, $rOptions);

        return $view -> url($route_name, $rParams, $rOptions);          

    }
?>

<div class="row">
    <div class="row-12">
        <ul class="nav nav-pills navbar-right">
            <?php 
            $uri = $_SERVER['REQUEST_URI'];
            $tabs = "";
            $activeMode = 'active';
            foreach($manager['modes'] as $mode_key => $mode) { 
                $li_class = "";
                $link = getRouteLink($this, $mode['route'], $params, $options);

                if($uri == $link) {
                    $activeMode = $mode_key;
                    $li_class= "active";
                }
                $tabs .= '<li class="'.$li_class.'"><a href="'.$link.'">';
                if(isset($mode['glyph'])) $tabs .= '<span class="glyphicon glyphicon-'.$mode['glyph'].'"></span>';
                $tabs .= $mode['label']."</a></li>".PHP_EOL;
            }
            echo $tabs;
            ?>
            <li class="dropdown">
                <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                  Actions <span class="caret"></span>
                </a>
                <ul class="dropdown-menu">
                    <li><a href="<?php echo $deleteAllLink; ?>">Delete All</a></li>
                </ul>
            </li>
        </ul>
    </div>
</div>

<?php 
if($rows -> getTotalItemCount() > 0) : 
    if($manager['thumbnail_field']['active'] == true) {
        $thumbnail_details = $manager['thumbnail_field']['details'];
    }
    if($manager['title_field']['active'] == true) {
        $title_details = $manager['title_field']['details'];
    }
?>  
<div class="table-responsive">
<table class="table table-hover">
    <thead>
        <tr>
            <th></th>
            <?php 

            if($manager['thumbnail_field']['active'] == true) { 
                echo "<th>{$thumbnail_details['label']}</th>";
            }

            if($manager['title_field']['active'] == true) {
                echo "<th>{$title_details['label']}</th>";
            }

            ?>
            <th>&nbsp;</th>
        </tr>
    </thead>
    <tbody>
        <?php 
        $options = $route['options'];
        $params = $route['params'];
        foreach($rows as $row): 
            $rowClass = array();
            if($row -> deleted == 1) $rowClass[] = 'danger';
            if($row -> status == 0) $rowClass[] = 'warning';

            $params['id'] = $row -> id;
            $params['action'] = 'unlock';
            $unlock_link = $this -> url($mainRouteName, $params, $options);
        ?>
        <tr class="<?php echo implode(" ", $rowClass); ?>" data-id="<?php echo $row -> id; ?>">
            <td>
            <?php
                if($row -> locked == 1) {
                    echo '<a href="'.$unlock_link.'" alt="Unlock"><span class="glyphicon glyphicon-lock"></span></a>';
                }
            ?>
            </td>
            <?php 
                if($manager['thumbnail_field']['active'] == true) { 
                    $imgThumbnail = str_replace("source/", "thumbs/", $row -> $thumbnail_details['field']);
                    echo "<td><img src=\"$imgThumbnail\" /></td>";
                }
                if($manager['title_field']['active'] == true) {
                    echo "<td>".$this -> escapeHtml($row -> $title_details['field'])."</td>";
                }
            ?>
            <td>
                <?php
                $mode = $manager['modes'][$activeMode];
                if(count($mode['links'])) {
                    $m_links = array_reverse($mode['links']);
                    $links_html = "";
                    foreach($m_links as $mlKey => $mLink) {
                        if(isset($mLink['type']) && $mLink['type'] == 'from_conditional_record') {
                            $value = $row -> $mLink['value'];
                            if(isset($mLink['case'][$value])) {
                                $mLink = $mLink['case'][$value];
                            } else continue;
                        }
                        $link = getRouteLink($this, $mLink['route'], $params, $options, $row);
                        $links_html .= '<a class="btn btn-default btn-sm" href="'.$link.'">';
                        if(isset($mLink['glyph'])) $links_html .= '<span class="glyphicon glyphicon-'.$mLink['glyph'].'"></span>';
                        $links_html .= $mLink['label']."</a>".PHP_EOL;
                    }                    
                    echo $links_html;
                }
                ?>
            </td>
        </tr>
        <?php endforeach; ?>
    </tbody>
</table>
</div>

<?php
    $params['action'] = 'index';
    unset($params['id']);
    echo $this->paginationControl(
        $rows,
        // the scrolling style
        'sliding',
        // the partial to use to render the control
        array('partial/paginator.phtml', 'Application'),
        // the route to link to when a user clicks a control link
        array(
            'route' => $mainRouteName,
            'params' => $params, 
            'options' => $options
        )
    );
else:
    echo "<div class=\"well well-sm\">No Records Found</div>";
endif;